export const INIT_SAVE_NOTES_VALUE = "INIT_GET_NOTES_VALUE";
export const SAVE_NOTES_VALUE_SUCCESSFULL = "SAVE_NOTES_VALUE_SUCCESSFULL";
export const SAVE_NOTES_VALUE_FAILED = "SAVE_NOTES_VALUE_FAILED";
