export const INIT_GET_LIST_DATA = "INIT_GET_LIST_DATA";

export const FETCHING_GET_LIST_DATA = "FETCHING_GET_LIST_DATA";

export const FETCHING_GET_LIST_DATA_SUCCESS = "FETCHING_GET_LIST_DATA_SUCCESS";

export const FETCHING_GET_LIST_DATA_FAILED = "FETCHING_GET_LIST_DATA_FAILED";
